/*
==============================================================================
Exploratory Data Analysis (EDA)
==============================================================================
Goal: get familiar with the dataset before doing any deeper analysis -
what tables/columns exist, what the dimensions and measures look like,
what time period the data covers, and where the big numbers are.
==============================================================================
*/

-- ---------------------------------------------------------------------------
-- 1. Database exploration - what are we working with?
-- ---------------------------------------------------------------------------

-- all tables in the database
SELECT
table_catalog,
table_schema,
table_name,
table_type
FROM INFORMATION_SCHEMA.TABLES

-- columns of dim_customers
SELECT
column_name,
data_type,
is_nullable,
character_maximum_length
FROM INFORMATION_SCHEMA.COLUMNS
WHERE table_name = 'dim_customers'


-- ---------------------------------------------------------------------------
-- 2. Dimensions exploration
-- use dimensions to group up, use measures for how many/how much
-- ---------------------------------------------------------------------------

-- unique countries customers come from
SELECT DISTINCT country
FROM gold.dim_customers
ORDER BY country

-- unique category / subcategory / product combinations
SELECT DISTINCT category, subcategory, product_name
FROM gold.dim_products
ORDER BY 1, 2, 3 -- can order by column position instead of names


-- ---------------------------------------------------------------------------
-- 3. Date range exploration
-- ---------------------------------------------------------------------------

-- first and last order date + how many months of data we have
SELECT
MIN(order_date) first_order_date,
MAX(order_date) last_order_date,
DATEDIFF(month, MIN(order_date), MAX(order_date)) order_range_months
FROM gold.fact_sales

-- youngest / oldest customer based on birthdate
SELECT
MIN(birthdate) oldest_birthdate,
DATEDIFF(year, MIN(birthdate), GETDATE()) oldest_age,
MAX(birthdate) youngest_birthdate,
DATEDIFF(year, MAX(birthdate), GETDATE()) youngest_age
FROM gold.dim_customers


-- ---------------------------------------------------------------------------
-- 4. Measures exploration
-- the "big numbers" - highest level of aggregation
-- (eliminate duplicates first by checking fact_sales)
-- ---------------------------------------------------------------------------

SELECT COUNT(DISTINCT order_number) total_orders
FROM gold.fact_sales

-- one combined report with all key business measures
SELECT 'Total Sales' as measure_name, SUM(sales_amount) measure_value
FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity', SUM(quantity)
FROM gold.fact_sales
UNION ALL
SELECT 'Average Price', AVG(price)
FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders', COUNT(DISTINCT order_number)
FROM gold.fact_sales
UNION ALL
SELECT 'Total Products', COUNT(product_name)
FROM gold.dim_products
UNION ALL
SELECT 'Total Customers', COUNT(customer_key)
FROM gold.dim_customers


-- ---------------------------------------------------------------------------
-- 5. Magnitude analysis
-- start from the fact table, LEFT JOIN dimensions, group by low-cardinality
-- dimensions to see how the numbers break down
-- ---------------------------------------------------------------------------

-- customers per country
SELECT
country,
COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- customers by gender
SELECT
gender,
COUNT(customer_key) total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- products per category
SELECT
category,
COUNT(product_key) total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- average cost per category
SELECT
category,
AVG(cost) avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- total revenue per category
SELECT
category,
SUM(sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key=p.product_key
GROUP BY category
ORDER BY total_revenue DESC

-- total revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key=c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- items sold per country
SELECT
c.country,
COUNT(f.quantity) item_qty
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key=c.customer_key
GROUP BY c.country
ORDER BY item_qty DESC


-- ---------------------------------------------------------------------------
-- 6. Ranking analysis - Top N / Bottom N
-- ---------------------------------------------------------------------------

-- top 5 product subcategories by revenue
SELECT TOP 5
p.subcategory,
SUM(sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key=p.product_key
GROUP BY p.subcategory
ORDER BY total_revenue DESC

-- same idea, but with a window function (useful for more complex reports
-- where you need the ranking alongside other columns)
SELECT * FROM (
SELECT
p.product_name,
SUM(sales_amount) total_revenue,
DENSE_RANK() OVER (ORDER BY SUM(sales_amount) DESC) rank_products
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key=p.product_key
GROUP BY p.product_name
) t
WHERE rank_products <= 5

-- 5 worst-performing products by revenue
SELECT TOP 5
p.product_name,
SUM(sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON f.product_key=p.product_key
GROUP BY p.product_name
ORDER BY total_revenue

-- top 10 customers by revenue
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(sales_amount) total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key=c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC

-- 3 customers with the fewest orders placed
SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT order_number) orders_qty
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c
ON f.customer_key=c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY orders_qty
